### ISSUE TITLE
geotools maven repo address has changed

### ISSUE THREAD

**Issue by mikekonikoff** [OpenGeoportal/OGP2#25]
geotools jars show up as missing with the current configuration.

OpenGeo maven repository has changed from http://repo.opengeo.org to http://repo.boundlessgeo.com/main - as documented here http://docs.geotools.org/latest/userguide/tutorial/quickstart/maven.html

**Comment by barneynibbs** [comment]
I am trying to build OpenGeoportal and keep getting the ERROR on the org.geotools stuff not being found. I can see in the POM file where http://repo.opengeo.org is called, but simply changing that URL to http://repo.boundlessgeo.com/main does not resolve these errors. What do I need to do in the POM file so that OGP2 will build correctly?

Thanks.
Bill Dickinson Jr.
Principal GIS Engineer, Exceptional Software
(bill.dickinson@exceptionalsoftware.com)
